### ISSUE TITLE
Improve Weather widget

### ISSUE THREAD

**Issue by gholadr** [gholadr/smogalert#27]
add logic to handle no data returned from the weather service. 
2. run the weather update with AsyncTask (as opposed to android.os.Handler). 
3. Run AsyncTask onResume only (as opposed to running the Handler every 60 secs
4. the layout UI still feels weird to me. I think we need to group the 2 elements closer together.

example of an improved UI

<img width="217" alt="screen shot 2016-08-04 at 7 28 07 pm" src="https://cloud.githubusercontent.com/assets/4038613/17402788/14b10e10-5a7f-11e6-91a2-a95dcdaaf437.png">

**Comment by AlecksJohanssen** [comment]
Hello Mr @gholadr  I have already fixed the Weather. Could you please check it out ?

**Comment by AlecksJohanssen** [comment]
I just removed the "AQI Years 2016" by setting it to null. Check it out too :P sorry I have to push it in Weather Branch :(
