### ISSUE TITLE
Last 24 Graph

### ISSUE THREAD

**Issue by gholadr** [gholadr/smogalert#29]
I've noticed a few issues with it:
1. if latest sample is from 10PM, then the data should start at 10AM
2. Data average seems wrong, I've just checked the data returned by the server and average for the last 4 hours is 64, yet the graph shows 94
3. Please remove `AQI year 2017`
4. 12PM on the graph shows as 0PM

**Comment by AlecksJohanssen** [comment]
Hello Mr @gholadr  I have already fixed Last 24 Hours Graph. Could you please check it out ?

**Comment by gholadr** [comment]
![screenshot_20160816-233214](https://cloud.githubusercontent.com/assets/4038613/17716657/f15a4e6a-6409-11e6-8a22-96713862a6a6.png)
hey guys, can you please submit a PR for this? the graph shows weird stuff on the x-axis
